### PR TITLE
Do CI on all branches

### PR DESCRIPTION
**Pull request by nethsix**
# DO NOT MERGE YET: Under review

If you merge, nothing bad happens

Update circle.yml:

* Remove branch definitions so that CI is performed on all branches
* Change 'git checkout' to use $CIRCLE_BRANCH

### CODE REVIEW

**Comment by nethsix** [comment]
@chrhansen I have updated the circle.yml to test the code of the pull request instead of from the master (which is incorrect as you pointed out).

Please help me eyeball it when you have time. I have pasted the command line here and sprinkled some comments to make it an easier read hopefully:

* docker run: Runs docker image
* -e CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME -e CIRCLE_BRANCH=$CIRCLE_BRANCH: Pass info to docker container about which repo (the person who pull requested), and which branch (pull requested)
* -it nethsix/ruby-tensorflow-ubuntu:0.0.1.a: The docker image pre-built with Tensorflow to run
* /bin/bash -l -c: run with bash within the docker container
* "mkdir -p /repos/ruby-tensorflow/circle-ci && ... ": Create a directory under /repos/ruby-tensorflow to fetch repo/branch for testing. ruby-2.2.4 with gemset ruby-tensorflow is also selected since we cd'ed into /repos/ruby-tensorflow/
* "cd /repos/ruby-tensorflow/circle-ci && git clone $CIRCLE_REPOSITORY_URL && cd /repos/ruby-tensorflow/circle-ci/ruby-tensorflow && git fetch && git checkout $CIRCLE_BRANCH && git pull && ...": Pull the code to be tested
* "bundle install && cd /repos/ruby-tensorflow/circle-ci/ruby-tensorflow/ext/sciruby/tensorflow_c && ruby extconf.rb && make && make install && cd /repos/ruby-tensorflow/circle-ci/ruby-tensorflow && bundle exec rake install && bundle exec rspec": build,  install, and run rspec

**Comment by chrhansen** [comment]
@nethsix thanks for the explanation, I don't have a lot of experience with Docker though. I'm currently running the `docker run -e ...` on my own machine, to see what the heck happens. In the meantime, the comments/questions I have are:

- For readability, would it be possible to split the `docker run -e ...` into separate lines (is this the newline command? `&& \`), like how @geoffreylitt mentioned https://github.com/Arafatk/tensorflow.rb/pull/37#issuecomment-235784193? 
- Again, I might be mixing the wrong things, but shouldn't/couldn't `/repos/ruby-tensorflow` be updated to `/repos/tensorflow.rb`
- I guess my last comment would be to add badges like https://github.com/Arafatk/tensorflow.rb/pull/37#issuecomment-235807658 to the README :)

**Comment by chrhansen** [comment]
@nethsix @Arafatk once this PR is ready and merged, I think we can safely trash https://github.com/Arafatk/tensorflow.rb/pull/31 and thank @nethsix for saving us all from an untested repo!

**Comment by nethsix** [comment]
@chrhansen Thanks! Having another smart person (not necessarily an expert) to eyeball through things is always useful.

1. I read @geoffreylitt 's suggestion, and have replied to it; basically docker does not save results of a run so for now I'm chaining those commands.
2. `/repos/ruby-tensorflow` is the directory within the Docker image itself so I guess leaving it the name as `ruby-tensorflow` is fine. I remember your comment about something similar in the Dockerfile, which I will update, and rebuild.
3. Yes! The badge. I've added in another local branch. I will move it to this same pull request.

**Pull request closed without merging**
