### PR TITLE
Add circle ci yml

### PR DESCRIPTION
**Pull request by nethsix**
* Use Dockerfile to build docker image nethsix/ruby-tensorflow-ubuntu:0.0.1
* Run specs in the docker image

### CODE REVIEW

**Comment by Arafatk** [comment]
@nethsix Thanks, can I merge this ?

**Comment by nethsix** [comment]
@Arafatk If everyone's ok with Circle CI, you can first sign up for CircleCI here with a few clicks: https://github.com/integrations/circle-ci

After that, at the dashboard:

1. Select yourself
2. Select ruby-tensorflow repo

That should be it. You can then merge. It almost does nothing for now, because circle.yml config is set to perform CI only for branches that contains the string 'circle_ci'. Thus only the CI will happen for this merged branch (you may have to manually trigger it from the dashboard)

**Comment by nethsix** [comment]
@Arafatk Thanks! I'll do another pull request with a new circle.yml within a day or two, if you have signed/set up Circle CI then when I do the pull request we should be able to see CircleCI perform the build and tests (fingers crossed).

**Comment by chrhansen** [comment]
@Arafatk great to see you made it work using Docker! 

I have two questions though:

- Could you set the image up so that it pulls from the branch that it is run on? Right not it just pulls the default branch from `git clone https://github.com/Arafatk/ruby-tensorflow.git` (which should be `../tensorflow.rb` btw.), so it will pull from the master branch instead of the branch of the current PR. 
- I think we should recommend in our installation instructions to also use Docker for building setting up TensorFlow

**Comment by nethsix** [comment]
@chrhansen  

* Thanks for pointing out that I need to pull from the branch that it is run from! Will work on this.
* I think Docker is nice, I used it when trying out Tensorflow in Python, but it requires people to download, so perhaps we can leave both there but work on the order, e.g., Docker instructions first

**Pull request merged**
